import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "Jahanzaib Shakeel | Space Portfolio",
  description: "Welcome to my space-themed Full-Stack & iOS Developer portfolio.",
  keywords: [
    "reactjs",
    "nextjs",
    "vercel",
    "react",
    "space-portfolio",
    "portfolio",
    "react-icons",
    "cn",
    "clsx",
    "3d-portfolio",
    "3d-website",
    "sonner",
    "framer-motion",
    "motion",
    "animation",
    "heroicons",
    "next-themes",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "eslint",
    "html",
    "css",
    "swift",
    "swiftui",
    "c#",
    "dotnet",
    "asp.net core",
    "flutter"
  ] as Array<string>,
  authors: {
    name: "Jahanzaib Shakeel",
    url: "https://github.com/JahanzaibDev",
  },
} as const;
